# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d1cc7a15a37664a831f33dc6f46ac34f1bab9e5de4b2a5491c8e203280eb294e22e8bb4490409221d8848153f3b6109843c9636e36325af108dce88bc78c03a

test:
  secret_key_base: fd812538f31fc7b1a2f5d7c8aaac7e03be0d3a9f74f9f73db7c73d6f32c3930a4fc36ca81cdce6965da4edea7554ed5abf3a1b7142c876f7445e976f7d8e2113

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
